import type { Store } from "@/types";

export let stores: Store[] = [
  {
    id: "store-001",
    name: "SenParts Dakar",
    code: "STR-DK",
    address: {
      street: "123 Avenue Cheikh Anta Diop",
      city: "Dakar",
      state: "Dakar",
      postalCode: "11000",
      country: "Sénégal",
    },
    phone: "+221 33 800 00 01",
    email: "dakar@senparts.sn",
    isActive: true,
    warehouseCount: 2,
    logoUrl: null,
    ninea: null,
    rccm: null,
    taxId: null,
    proformaPrefix: null,
    invoicePrefix: "FAC-DK",
    depositPrefix: null,
    creditNotePrefix: null,
    orderPrefix: null,
    defaultPaymentTerms: null,
    defaultProformaValidity: null,
    defaultInvoiceTemplate: null,
    defaultInvoiceNotes: null,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2026-02-15T09:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "store-002",
    name: "SenParts Saint-Louis",
    code: "STR-SL",
    address: {
      street: "45 Rue de France",
      city: "Saint-Louis",
      state: "Saint-Louis",
      postalCode: "32000",
      country: "Sénégal",
    },
    phone: "+221 33 900 00 01",
    email: "saintlouis@senparts.sn",
    isActive: true,
    warehouseCount: 2,
    logoUrl: null,
    ninea: "005234567 2G4",
    rccm: "SN-SLO-2024-B-67890",
    taxId: null,
    proformaPrefix: null,
    invoicePrefix: "FAC-SL",
    depositPrefix: null,
    creditNotePrefix: null,
    orderPrefix: null,
    defaultPaymentTerms: 45,
    defaultProformaValidity: null,
    defaultInvoiceTemplate: null,
    defaultInvoiceNotes: null,
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2026-01-20T11:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "store-003",
    name: "SenParts Thiès",
    code: "STR-TH",
    address: {
      street: "12 Boulevard de la Gare",
      city: "Thiès",
      state: "Thiès",
      postalCode: "21000",
      country: "Sénégal",
    },
    phone: "+221 33 850 00 01",
    email: "thies@senparts.sn",
    isActive: false,
    warehouseCount: 1,
    logoUrl: null,
    ninea: null,
    rccm: null,
    taxId: null,
    proformaPrefix: null,
    invoicePrefix: null,
    depositPrefix: null,
    creditNotePrefix: null,
    orderPrefix: null,
    defaultPaymentTerms: null,
    defaultProformaValidity: null,
    defaultInvoiceTemplate: null,
    defaultInvoiceNotes: null,
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2026-02-28T16:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
];

export function setStores(updated: Store[]) {
  stores = updated;
}
